import { isNode } from "./env.ts";

/** The slice of the wasm-bindgen glue this package uses. */
export interface WasmModule {
  Readmeter: new (configJson: string, bundle: Uint8Array) => WasmHandle;
  initSync(input: { module: BufferSource }): unknown;
}

export interface WasmHandle {
  record(rawJson: string): string;
  flush(nowMs: number): Uint8Array | undefined;
  activeRules(): string[];
  free(): void;
}

const cache = new Map<string, Promise<WasmModule>>();

/**
 * Node-only module load. `new Function` keeps the specifier out of the
 * bundler graph: a literal `import("node:fs")` makes Vite warn that the
 * builtin cannot be resolved for the browser.
 */
function importSpecifier<T>(specifier: string): Promise<T> {
  const load = new Function("specifier", "return import(specifier)") as (specifier: string) => Promise<T>;
  return load(specifier);
}

function cacheKey(dev: boolean, override?: URL): string {
  if (override) return override.href;
  if (isNode() && process.env.READMETER_WASM_DIR) return process.env.READMETER_WASM_DIR;
  return dev ? "dev" : "prod";
}

/** `READMETER_WASM_DIR` is a Node override. Browsers always use the packaged files. */
async function nodeDir(override?: URL): Promise<URL | undefined> {
  if (override) return override;
  if (!isNode() || !process.env.READMETER_WASM_DIR) return undefined;
  const path = await importSpecifier<typeof import("node:path")>("node:path");
  const url = await importSpecifier<typeof import("node:url")>("node:url");
  const raw = process.env.READMETER_WASM_DIR;
  const dir = raw.endsWith(path.sep) ? raw : raw + path.sep;
  return url.pathToFileURL(dir);
}

/** Node file URL of the packaged `.wasm`. Not used in the browser (no `new URL` asset). */
async function nodeWasmFile(dev: boolean, dir?: URL): Promise<URL> {
  if (dir) {
    const url = await importSpecifier<typeof import("node:url")>("node:url");
    const path = await importSpecifier<typeof import("node:path")>("node:path");
    const base = url.fileURLToPath(dir);
    const file = path.join(base, "readmeter_wasm_bg.wasm");
    return url.pathToFileURL(file);
  }
  const path = await importSpecifier<typeof import("node:path")>("node:path");
  const url = await importSpecifier<typeof import("node:url")>("node:url");
  const here = url.fileURLToPath(import.meta.url);
  const rel = dev ? "../../wasm/dev/readmeter_wasm_bg.wasm" : "../../wasm/prod/readmeter_wasm_bg.wasm";
  return url.pathToFileURL(path.resolve(path.dirname(here), rel));
}

function decodeBase64(encoded: string): Uint8Array {
  const binary = atob(encoded);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

async function loadGlue(dev: boolean, dir?: URL): Promise<WasmModule> {
  try {
    if (dir) {
      const href = new URL("readmeter_wasm.js", dir).href;
      return (await import(/* @vite-ignore */ href)) as WasmModule;
    }
    // Two literal dynamic imports: bundlers code-split, and only the taken branch loads.
    return (
      dev
        ? await import("../../wasm/dev/readmeter_wasm.js")
        : await import("../../wasm/prod/readmeter_wasm.js")
    ) as WasmModule;
  } catch (error) {
    const where = dir ? new URL("readmeter_wasm.js", dir).href : dev ? "dev" : "prod";
    const detail = error instanceof Error ? error.message : String(error);
    throw new Error(`wasm glue missing (${where}): ${detail}`);
  }
}

async function readWasm(dev: boolean, dir?: URL): Promise<Uint8Array> {
  if (isNode()) {
    const url = await nodeWasmFile(dev, dir);
    try {
      const fs = await importSpecifier<typeof import("node:fs")>("node:fs");
      return new Uint8Array(fs.readFileSync(url));
    } catch (error) {
      const detail = error instanceof Error ? error.message : String(error);
      throw new Error(`wasm file missing at ${url.href}: ${detail}`);
    }
  }
  // Literal imports so a bundler emits two chunks. Vite pre-bundling rewrites
  // `new URL("...wasm", import.meta.url)` away from the file, so the bytes live in JS.
  // @ts-ignore inline.js is generated by scripts/build.sh and is absent until the package is built
  const encoded = (dev ? await import("../../wasm/dev/inline.js") : await import("../../wasm/prod/inline.js")) as { default: string };
  if (typeof encoded.default !== "string" || encoded.default.length === 0) {
    throw new Error(`wasm inline missing (${dev ? "dev" : "prod"})`);
  }
  return decodeBase64(encoded.default);
}

async function loadBuild(dev: boolean, dir?: URL): Promise<WasmModule> {
  const glue = await loadGlue(dev, dir);
  const bytes = await readWasm(dev, dir);
  // Copy into a plain ArrayBuffer. Node's Buffer is a Uint8Array over a
  // shared pool, and TypeScript will not treat that view as a BufferSource.
  const module = new ArrayBuffer(bytes.byteLength);
  new Uint8Array(module).set(bytes);
  glue.initSync({ module });
  return glue;
}

/**
 * Loads prod or dev wasm. Node reads the `.wasm` file (or `READMETER_WASM_DIR`).
 * The browser decodes the packaged base64 module and calls `initSync`.
 * `initSync` is once per glue module (the glue's own guard).
 */
export function loadWasm(dev: boolean, override?: URL): Promise<WasmModule> {
  const key = cacheKey(dev, override);
  const hit = cache.get(key);
  if (hit) return hit;
  const pending = nodeDir(override)
    .then((dir) => loadBuild(dev, dir))
    .catch((error: unknown) => {
      cache.delete(key);
      throw error;
    });
  cache.set(key, pending);
  return pending;
}
