/* Readmeter C ABI. Generated by cbindgen from crates/bindings/ffi; do not edit. */

#ifndef READMETER_H
#define READMETER_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

enum RmStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  RM_STATUS_OK = 0,
  RM_STATUS_NULL_ARGUMENT = 1,
  RM_STATUS_ERROR = 2,
  RM_STATUS_PANIC = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum RmStatus RmStatus;
#else
typedef int32_t RmStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Opaque client handle.
typedef struct RmClient RmClient;

// Byte buffer owned by Rust.
typedef struct {
  uint8_t *ptr;
  size_t len;
  size_t cap;
} RmBuf;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Creates a client. On success `*out` receives a handle to free with
// `rm_client_free`.
//
// `config_json` is UTF-8 JSON. `bundle` is the bytes of `bundle.bin`.
//
// # Safety
// Pointers must be valid for their lengths; `out` must be writable.
RmStatus rm_client_new(const uint8_t *config_json,
                       size_t config_len,
                       const uint8_t *bundle,
                       size_t bundle_len,
                       RmClient **out);

// Records one raw call. `*findings_out` receives a JSON array of findings
// from local rules (possibly `[]`). Each object has `rule`, `severity`,
// `template`, `message` and `wasted` (unit name to an integer). `evidence`
// is not included; it stays in the batch.
//
// # Safety
// `client` must come from `rm_client_new`; other pointers valid as usual.
RmStatus rm_client_record(RmClient *client,
                          const uint8_t *raw_json,
                          size_t raw_len,
                          RmBuf *findings_out);

// Drains buffered events into an encoded batch to POST to ingest.
// `*batch_out` has `len == 0` when there is nothing to send.
//
// # Safety
// `client` must come from `rm_client_new`; `batch_out` must be writable.
RmStatus rm_client_flush(RmClient *client, uint64_t now_ms, RmBuf *batch_out);

// Copies the calling thread's last error message into `*out`.
//
// # Safety
// `out` must be writable.
RmStatus rm_last_error(RmBuf *out);

// # Safety
// `buf` must come from this library and not be freed twice.
void rm_buf_free(RmBuf buf);

// # Safety
// `client` must come from `rm_client_new` and not be used afterwards.
void rm_client_free(RmClient *client);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* READMETER_H */
