/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AcceptInvitationIdRouteImport } from './routes/accept-invitation.$id'
import { Route as InviteIdRouteImport } from './routes/invite.$id'
import { Route as AppWSlugRouteImport } from './routes/_app/w/$slug'
import { Route as AppWSlugIndexRouteImport } from './routes/_app/w/$slug/index'
import { Route as AppWSlugCostsRouteImport } from './routes/_app/w/$slug/costs'
import { Route as AppWSlugEventsRouteImport } from './routes/_app/w/$slug/events'
import { Route as AppWSlugIntegrationsRouteImport } from './routes/_app/w/$slug/integrations'
import { Route as AppWSlugKeysRouteImport } from './routes/_app/w/$slug/keys'
import { Route as AppWSlugMembersRouteImport } from './routes/_app/w/$slug/members'
import { Route as AppWSlugOverviewRouteImport } from './routes/_app/w/$slug/overview'
import { Route as AppWSlugRulesRouteImport } from './routes/_app/w/$slug/rules'
import { Route as AppWSlugSettingsRouteImport } from './routes/_app/w/$slug/settings'
import { Route as AppWSlugFindingsIndexRouteImport } from './routes/_app/w/$slug/findings/index'
import { Route as AppWSlugFindingsIdRouteImport } from './routes/_app/w/$slug/findings/$id'
import { Route as AppWSlugProjectsIndexRouteImport } from './routes/_app/w/$slug/projects/index'
import { Route as AppWSlugProjectsProjectIdRouteImport } from './routes/_app/w/$slug/projects/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteIdRoute = InviteIdRouteImport.update({
  id: '/invite/$id',
  path: '/invite/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWSlugRoute = AppWSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppWSlugIndexRoute = AppWSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWSlugRoute,
} as any)
const AppWSlugCostsRoute = AppWSlugCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AppWSlugRoute,
} as any)
const AppWSlugEventsRoute = AppWSlugEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppWSlugRoute,
} as any)
const AppWSlugIntegrationsRoute = AppWSlugIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppWSlugRoute,
} as any)
const AppWSlugKeysRoute = AppWSlugKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppWSlugRoute,
} as any)
const AppWSlugMembersRoute = AppWSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppWSlugRoute,
} as any)
const AppWSlugOverviewRoute = AppWSlugOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppWSlugRoute,
} as any)
const AppWSlugRulesRoute = AppWSlugRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppWSlugRoute,
} as any)
const AppWSlugSettingsRoute = AppWSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppWSlugRoute,
} as any)
const AppWSlugFindingsIndexRoute = AppWSlugFindingsIndexRouteImport.update({
  id: '/findings/',
  path: '/findings/',
  getParentRoute: () => AppWSlugRoute,
} as any)
const AppWSlugFindingsIdRoute = AppWSlugFindingsIdRouteImport.update({
  id: '/findings/$id',
  path: '/findings/$id',
  getParentRoute: () => AppWSlugRoute,
} as any)
const AppWSlugProjectsIndexRoute = AppWSlugProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppWSlugRoute,
} as any)
const AppWSlugProjectsProjectIdRoute =
  AppWSlugProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppWSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account': typeof AppAccountRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/invite/$id': typeof InviteIdRoute
  '/w/$slug': typeof AppWSlugRouteWithChildren
  '/w/$slug/costs': typeof AppWSlugCostsRoute
  '/w/$slug/events': typeof AppWSlugEventsRoute
  '/w/$slug/integrations': typeof AppWSlugIntegrationsRoute
  '/w/$slug/keys': typeof AppWSlugKeysRoute
  '/w/$slug/members': typeof AppWSlugMembersRoute
  '/w/$slug/overview': typeof AppWSlugOverviewRoute
  '/w/$slug/rules': typeof AppWSlugRulesRoute
  '/w/$slug/settings': typeof AppWSlugSettingsRoute
  '/w/$slug/': typeof AppWSlugIndexRoute
  '/w/$slug/findings/$id': typeof AppWSlugFindingsIdRoute
  '/w/$slug/projects/$projectId': typeof AppWSlugProjectsProjectIdRoute
  '/w/$slug/findings/': typeof AppWSlugFindingsIndexRoute
  '/w/$slug/projects/': typeof AppWSlugProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account': typeof AppAccountRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/invite/$id': typeof InviteIdRoute
  '/w/$slug/costs': typeof AppWSlugCostsRoute
  '/w/$slug/events': typeof AppWSlugEventsRoute
  '/w/$slug/integrations': typeof AppWSlugIntegrationsRoute
  '/w/$slug/keys': typeof AppWSlugKeysRoute
  '/w/$slug/members': typeof AppWSlugMembersRoute
  '/w/$slug/overview': typeof AppWSlugOverviewRoute
  '/w/$slug/rules': typeof AppWSlugRulesRoute
  '/w/$slug/settings': typeof AppWSlugSettingsRoute
  '/w/$slug': typeof AppWSlugIndexRoute
  '/w/$slug/findings/$id': typeof AppWSlugFindingsIdRoute
  '/w/$slug/projects/$projectId': typeof AppWSlugProjectsProjectIdRoute
  '/w/$slug/findings': typeof AppWSlugFindingsIndexRoute
  '/w/$slug/projects': typeof AppWSlugProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/account': typeof AppAccountRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/invite/$id': typeof InviteIdRoute
  '/_app/w/$slug': typeof AppWSlugRouteWithChildren
  '/_app/w/$slug/costs': typeof AppWSlugCostsRoute
  '/_app/w/$slug/events': typeof AppWSlugEventsRoute
  '/_app/w/$slug/integrations': typeof AppWSlugIntegrationsRoute
  '/_app/w/$slug/keys': typeof AppWSlugKeysRoute
  '/_app/w/$slug/members': typeof AppWSlugMembersRoute
  '/_app/w/$slug/overview': typeof AppWSlugOverviewRoute
  '/_app/w/$slug/rules': typeof AppWSlugRulesRoute
  '/_app/w/$slug/settings': typeof AppWSlugSettingsRoute
  '/_app/w/$slug/': typeof AppWSlugIndexRoute
  '/_app/w/$slug/findings/$id': typeof AppWSlugFindingsIdRoute
  '/_app/w/$slug/projects/$projectId': typeof AppWSlugProjectsProjectIdRoute
  '/_app/w/$slug/findings/': typeof AppWSlugFindingsIndexRoute
  '/_app/w/$slug/projects/': typeof AppWSlugProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/account'
    | '/accept-invitation/$id'
    | '/invite/$id'
    | '/w/$slug'
    | '/w/$slug/costs'
    | '/w/$slug/events'
    | '/w/$slug/integrations'
    | '/w/$slug/keys'
    | '/w/$slug/members'
    | '/w/$slug/overview'
    | '/w/$slug/rules'
    | '/w/$slug/settings'
    | '/w/$slug/'
    | '/w/$slug/findings/$id'
    | '/w/$slug/projects/$projectId'
    | '/w/$slug/findings/'
    | '/w/$slug/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/account'
    | '/accept-invitation/$id'
    | '/invite/$id'
    | '/w/$slug/costs'
    | '/w/$slug/events'
    | '/w/$slug/integrations'
    | '/w/$slug/keys'
    | '/w/$slug/members'
    | '/w/$slug/overview'
    | '/w/$slug/rules'
    | '/w/$slug/settings'
    | '/w/$slug'
    | '/w/$slug/findings/$id'
    | '/w/$slug/projects/$projectId'
    | '/w/$slug/findings'
    | '/w/$slug/projects'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_app/account'
    | '/accept-invitation/$id'
    | '/invite/$id'
    | '/_app/w/$slug'
    | '/_app/w/$slug/costs'
    | '/_app/w/$slug/events'
    | '/_app/w/$slug/integrations'
    | '/_app/w/$slug/keys'
    | '/_app/w/$slug/members'
    | '/_app/w/$slug/overview'
    | '/_app/w/$slug/rules'
    | '/_app/w/$slug/settings'
    | '/_app/w/$slug/'
    | '/_app/w/$slug/findings/$id'
    | '/_app/w/$slug/projects/$projectId'
    | '/_app/w/$slug/findings/'
    | '/_app/w/$slug/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
  InviteIdRoute: typeof InviteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/accept-invitation/$id': {
      id: '/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$id': {
      id: '/invite/$id'
      path: '/invite/$id'
      fullPath: '/invite/$id'
      preLoaderRoute: typeof InviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/w/$slug': {
      id: '/_app/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof AppWSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$slug/': {
      id: '/_app/w/$slug/'
      path: '/'
      fullPath: '/w/$slug/'
      preLoaderRoute: typeof AppWSlugIndexRouteImport
      parentRoute: typeof AppWSlugRoute
    }
    '/_app/w/$slug/costs': {
      id: '/_app/w/$slug/costs'
      path: '/costs'
      fullPath: '/w/$slug/costs'
      preLoaderRoute: typeof AppWSlugCostsRouteImport
      parentRoute: typeof AppWSlugRoute
    }
    '/_app/w/$slug/events': {
      id: '/_app/w/$slug/events'
      path: '/events'
      fullPath: '/w/$slug/events'
      preLoaderRoute: typeof AppWSlugEventsRouteImport
      parentRoute: typeof AppWSlugRoute
    }
    '/_app/w/$slug/integrations': {
      id: '/_app/w/$slug/integrations'
      path: '/integrations'
      fullPath: '/w/$slug/integrations'
      preLoaderRoute: typeof AppWSlugIntegrationsRouteImport
      parentRoute: typeof AppWSlugRoute
    }
    '/_app/w/$slug/keys': {
      id: '/_app/w/$slug/keys'
      path: '/keys'
      fullPath: '/w/$slug/keys'
      preLoaderRoute: typeof AppWSlugKeysRouteImport
      parentRoute: typeof AppWSlugRoute
    }
    '/_app/w/$slug/members': {
      id: '/_app/w/$slug/members'
      path: '/members'
      fullPath: '/w/$slug/members'
      preLoaderRoute: typeof AppWSlugMembersRouteImport
      parentRoute: typeof AppWSlugRoute
    }
    '/_app/w/$slug/overview': {
      id: '/_app/w/$slug/overview'
      path: '/overview'
      fullPath: '/w/$slug/overview'
      preLoaderRoute: typeof AppWSlugOverviewRouteImport
      parentRoute: typeof AppWSlugRoute
    }
    '/_app/w/$slug/rules': {
      id: '/_app/w/$slug/rules'
      path: '/rules'
      fullPath: '/w/$slug/rules'
      preLoaderRoute: typeof AppWSlugRulesRouteImport
      parentRoute: typeof AppWSlugRoute
    }
    '/_app/w/$slug/settings': {
      id: '/_app/w/$slug/settings'
      path: '/settings'
      fullPath: '/w/$slug/settings'
      preLoaderRoute: typeof AppWSlugSettingsRouteImport
      parentRoute: typeof AppWSlugRoute
    }
    '/_app/w/$slug/findings/': {
      id: '/_app/w/$slug/findings/'
      path: '/findings'
      fullPath: '/w/$slug/findings/'
      preLoaderRoute: typeof AppWSlugFindingsIndexRouteImport
      parentRoute: typeof AppWSlugRoute
    }
    '/_app/w/$slug/findings/$id': {
      id: '/_app/w/$slug/findings/$id'
      path: '/findings/$id'
      fullPath: '/w/$slug/findings/$id'
      preLoaderRoute: typeof AppWSlugFindingsIdRouteImport
      parentRoute: typeof AppWSlugRoute
    }
    '/_app/w/$slug/projects/': {
      id: '/_app/w/$slug/projects/'
      path: '/projects'
      fullPath: '/w/$slug/projects/'
      preLoaderRoute: typeof AppWSlugProjectsIndexRouteImport
      parentRoute: typeof AppWSlugRoute
    }
    '/_app/w/$slug/projects/$projectId': {
      id: '/_app/w/$slug/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/w/$slug/projects/$projectId'
      preLoaderRoute: typeof AppWSlugProjectsProjectIdRouteImport
      parentRoute: typeof AppWSlugRoute
    }
  }
}

interface AppWSlugRouteChildren {
  AppWSlugCostsRoute: typeof AppWSlugCostsRoute
  AppWSlugEventsRoute: typeof AppWSlugEventsRoute
  AppWSlugIntegrationsRoute: typeof AppWSlugIntegrationsRoute
  AppWSlugKeysRoute: typeof AppWSlugKeysRoute
  AppWSlugMembersRoute: typeof AppWSlugMembersRoute
  AppWSlugOverviewRoute: typeof AppWSlugOverviewRoute
  AppWSlugRulesRoute: typeof AppWSlugRulesRoute
  AppWSlugSettingsRoute: typeof AppWSlugSettingsRoute
  AppWSlugIndexRoute: typeof AppWSlugIndexRoute
  AppWSlugFindingsIdRoute: typeof AppWSlugFindingsIdRoute
  AppWSlugProjectsProjectIdRoute: typeof AppWSlugProjectsProjectIdRoute
  AppWSlugFindingsIndexRoute: typeof AppWSlugFindingsIndexRoute
  AppWSlugProjectsIndexRoute: typeof AppWSlugProjectsIndexRoute
}

const AppWSlugRouteChildren: AppWSlugRouteChildren = {
  AppWSlugCostsRoute: AppWSlugCostsRoute,
  AppWSlugEventsRoute: AppWSlugEventsRoute,
  AppWSlugIntegrationsRoute: AppWSlugIntegrationsRoute,
  AppWSlugKeysRoute: AppWSlugKeysRoute,
  AppWSlugMembersRoute: AppWSlugMembersRoute,
  AppWSlugOverviewRoute: AppWSlugOverviewRoute,
  AppWSlugRulesRoute: AppWSlugRulesRoute,
  AppWSlugSettingsRoute: AppWSlugSettingsRoute,
  AppWSlugIndexRoute: AppWSlugIndexRoute,
  AppWSlugFindingsIdRoute: AppWSlugFindingsIdRoute,
  AppWSlugProjectsProjectIdRoute: AppWSlugProjectsProjectIdRoute,
  AppWSlugFindingsIndexRoute: AppWSlugFindingsIndexRoute,
  AppWSlugProjectsIndexRoute: AppWSlugProjectsIndexRoute,
}

const AppWSlugRouteWithChildren = AppWSlugRoute._addFileChildren(
  AppWSlugRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppWSlugRoute: typeof AppWSlugRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppWSlugRoute: AppWSlugRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
  InviteIdRoute: InviteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
